#
# Module manifest for module 'DailyHealth'
#
# Generated by: adminjc
#
# Generated on: 1/8/2024
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'DailyHealth.psm1'

# Version number of this module.
ModuleVersion = '1.1.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop')

# ID used to uniquely identify this module
GUID = '28c77853-8e34-459f-b600-be7a68bdc10d'

# Author of this module
Author = 'Jeremy Crabtree'

# Company or vendor of this module
CompanyName = 'North Central Texas Emergency Communications District (NCT 9-1-1)'

# Copyright statement for this module
Copyright = '(c) NCT 9-1-1 All rights reserved.'

# Description of the functionality provided by this module
Description = @'
Collects health and status information from infrastructure systems and normalizes every
result onto one status vocabulary (success, warning, error, info) so unrelated sources can
be summarized and rendered together.

Collectors cover certificate expiration (public TLS endpoints and internal AD CS), URI and
DNS reachability probes, Veeam Backup and Replication job results, vCenter triggered alarms,
Cisco UCS Manager faults, ArcGIS Online service status, SolarWinds Orion down nodes, down
interfaces and active alerts, and building HVAC controller alarms.

Get-DailyStatus orchestrates the set: it reads a job configuration collection, dispatches
each entry to its collector as a background job, drains the jobs as they complete, and
attaches per-job severity counts and a worst-case overall health value.

Each collector reports failures as records rather than throwing, so one unreachable system
does not abort a run.
'@

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
#
# Deliberately not declared. The vendor modules below are each needed by exactly one
# collector, and listing them here would make the whole module fail to import on a host
# that only runs some of the checks:
#
#     VMware.PowerCLI                       Get-TriggeredVMWareAlarms
#     Cisco.UCS.Common, Cisco.UCSManager    Get-UCSHealth (imported inside the function)
#     SwisPowerShell                        New-SWISQuery and the Get-SWIS* collectors
#     Veeam.Backup.PowerShell               Get-AllVBRJobs (runs on the VBR server, not here)
#
# PKITools 1.6 is a hard requirement of the internal certificate path and is enforced by
# the #requires statement at the top of DailyHealth.psm1.
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @('System.Web')

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    # Orchestration
    'Get-DailyStatus'

    # Collectors - the set Get-DailyStatus dispatches by job type
    'Test-URIList'
    'Test-DNSServerRemote'
    'Get-TriggeredVMWareAlarms'
    'Get-AllVBRJobs'
    'Get-CertExpiration'
    'Get-UCSHealth'
    'Get-AGOStatus'
    'Get-SWISInterfacesDown'
    'Get-SWISNodesDown'
    'Get-SWISAlerts'
    'Get-HVACAlerts'

    # Severity normalization and rollup
    'Get-Severity'
    'Get-JobSummary'
    'Get-JobOverallHealth'

    # Supporting functions, usable directly
    'ConvertTo-Hashtable'
    'Invoke-WebRequestDH'
    'Get-ResponseContent'
    'Get-DecodedCertificate'
    'Get-InternalCertInfo'
    'Get-AGOEventStatus'
    'New-SWISQuery'
    'New-HVACResponse'
    'ConvertFrom-EventResponse'
    'ConvertFrom-EventList'
    'Write-JobDetails'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    'DailyHealth.psd1'
    'DailyHealth.psm1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @(
            'Monitoring'
            'HealthCheck'
            'Veeam'
            'VMware'
            'PowerCLI'
            'SolarWinds'
            'Orion'
            'Cisco'
            'UCS'
            'ArcGIS'
            'PKI'
            'Certificates'
            'DNS'
            'HVAC'
            'Windows'
        )

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
1.1.0
- Comment-based help added to every function.
- Invoke-WebRequestDH now installs the permissive certificate policy it compiles, so the
  SSL checks can read expired and untrusted certificates instead of failing the handshake.
  The policy and SecurityProtocol are both changed inside the try and restored in the
  finally. Request timeout raised from 2000 ms to 5000 ms, and the policy type is compiled
  once per session rather than on every call.
- Test-URIList no longer requires ComputerName. Omit it, or name the local machine, and the
  probe loop runs in the current session; the loop takes its inputs as parameters so the
  same block serves both paths. A dispatch failure now returns a record in the normal
  Status/URI/Proxy shape.
- Test-DNSServerRemote clears its status variable between iterations.
- Get-TriggeredVMWareAlarms disconnects only the sessions that actually connected.
- Get-AGOStatus evaluates each service against its own event list.
- ConvertFrom-EventList takes the controller IP as a parameter instead of reading it from
  the caller's scope.
- Get-AllVBRJobs reports a failed background job's own failure reason.
- Get-DailyStatus imports the module in every background job, handles an unrecognized job
  type without stalling the drain loop, and no longer aborts the run when a check returns
  nothing.
- Get-CertExpiration ExcludedTemplates now defaults to empty; supply the auto-enrolled
  template OIDs for the environment being checked or the internal report will be noisy.

1.0
- Initial version.
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        ExternalModuleDependencies = @(
            'VMware.PowerCLI'
            'Cisco.UCS.Common'
            'Cisco.UCSManager'
            'SwisPowerShell'
        )

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}